[project]
name = "messenger-project-phase-3-and-4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "fastapi[standard]>=0.141.1",
    "psycopg2-binary>=2.9.12",
    "psycopg[binary]>=3.3.4",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.52",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.1",
    "pytest>=8.0",
    "ruff>=0.16.0",
]
